const $ = id => document.getElementById(id);
const clean = value => typeof value === 'string' ? value.replace(/\\n/g, '\n').replace(/\*\*/g, '').trim() : '';
// Keep the shared page consistent with the native analysis block ledger.
function displaySections(sections, initial = []) {
 const key = text => clean(text).replace(/\s+/g, ' ');
 const seen = new Set(initial.map(key));
 return sections.filter(section => {
  const body = key(section.body);
  if (!body || body.includes('발표 뒤 확보한 현황이에요.') || seen.has(body)) return false;
  seen.add(body); return true;
 });
}
const node = (tag, text, cls) => { const e=document.createElement(tag); if(text!=null)e.textContent=clean(String(text)); if(cls)e.className=cls; return e; };
const safeURL = value => { try { const u=new URL(value); return u.protocol==='https:'?u.href:null; } catch { return null; } };
const stamp = value => { const d=new Date(value); return Number.isFinite(+d)?d.toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})+' KST':''; };
const amount = n => n.toLocaleString('ko-KR',{maximumFractionDigits:2});
const params=new URLSearchParams(location.search), kind=params.get('k')||'n', id=params.get('n')||'';
const canonical=new URL('https://withfindex.com/o/'); canonical.searchParams.set('k',kind); canonical.searchParams.set('n',id);
let article, selected='';
function source(parent,url,label='근거 원문 보기 ↗'){const href=safeURL(url);if(!href)return;const a=node('a',label,'source');a.href=href;a.target='_blank';a.rel='noopener noreferrer';parent.append(a);}
function card(title,cls=''){const e=node('section',null,'card '+cls);if(title)e.append(node('h2',title));return e;}
function prose(parent,text){for(const line of clean(text).split(/\n+/).filter(Boolean)){const pair=line.match(/^([^:]+):\s*([^:]+)\s*→\s*([^:]+)$/);if(pair){const a=number(pair[2]),b=number(pair[3]);if(a&&b&&a.unit===b.unit){parent.append(node('h3',pair[1]),bars([{label:'이전',value:a.value,text:pair[2]},{label:'이후',value:b.value,text:pair[3]}]));continue;}}parent.append(node('p',line));}}
function number(raw){const t=String(raw??'').trim().replace(/−/g,'-'),m=t.match(/^(\$)?([+-]?(?:\d{1,3}(?:,\d{3})+|\d+)(?:\.\d+)?)\s*([KMB%])?$/i);if(!m||m[1]&&m[3]==='%')return null;const suffix=(m[3]||'').toUpperCase(),value=Number(m[2].replace(/,/g,''))*({K:1e3,M:1e6,B:1e9}[suffix]||1);return Number.isFinite(value)?{value,unit:suffix==='%'?'%':m[1]?'USD':'number'}:null;}
function bars(rows){const box=node('div',null,'bars'),lo=Math.min(0,...rows.map(x=>x.value)),hi=Math.max(0,...rows.map(x=>x.value)),span=hi-lo||1;rows.forEach((p,i)=>{const row=node('div',null,'bar-row'),labels=node('div',null,'bar-label');labels.append(node('span',p.label),node('strong',p.text??amount(p.value)));const track=node('div',null,'track'),bar=node('span',null,'bar'+(i===rows.length-1?' last':'')),zero=node('i');bar.style.left=((Math.min(0,p.value)-lo)/span*100)+'%';bar.style.width=(Math.abs(p.value)/span*100)+'%';zero.style.left=(-lo/span*100)+'%';track.setAttribute('aria-hidden','true');track.append(bar,zero);row.append(labels,track);box.append(row);});box.append(node('small','막대는 0 기준 · 항목 안에서 같은 눈금으로 비교해요.'));return box;}
function figure(f){const e=card(f.label),actual=number(f.actual),rows=[];for(const [label,raw] of [['이전',f.previous],['예상',f.forecast],['발표',f.actual]]){const n=number(raw);if(n&&actual&&n.unit===actual.unit)rows.push({label,value:n.value,text:String(raw)});}if(rows.length>=2)e.append(bars(rows));else for(const [label,raw] of [['발표',f.actual],['예상',f.forecast],['이전',f.previous]])e.append(node('p',label+' · '+(raw??'미제공')));if(f.comparison)e.append(node('p',f.comparison));return e;}
function plot(points,unit='',comparison=[],time=false){const all=points.filter(p=>Number.isFinite(p.value));const wrap=node('div',null,'plot');if(all.length<2){wrap.append(node('p','표시할 관측값이 부족해요.'));return wrap;}
 const other=comparison.filter(p=>Number.isFinite(p.value)),values=[...all,...other].map(p=>p.value);if(!time)values.push(0);let lo=Math.min(...values),hi=Math.max(...values),pad=Math.max((hi-lo)*.08,Math.abs(hi)*.00001,1e-6);lo-=pad;hi+=pad;
 const W=620,H=230,L=74,R=12,T=12,B=28,ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox',`0 0 ${W} ${H}`);svg.setAttribute('role','img');svg.setAttribute('aria-label',`${unit} 흐름. 처음 ${amount(all[0].value)}, 마지막 ${amount(all.at(-1).value)}.`);
 const add=(tag,attrs,text)=>{const e=document.createElementNS(ns,tag);for(const [k,v] of Object.entries(attrs))e.setAttribute(k,String(v));if(text)e.textContent=text;svg.append(e);return e;};
 const xmin=time?all[0].t:0,xmax=time?all.at(-1).t:all.length-1,x=(p,i)=>L+((time?p.t:i)-xmin)/(xmax-xmin||1)*(W-L-R),y=v=>T+(hi-v)/(hi-lo)*(H-T-B);
 for(let i=0;i<4;i++){const v=lo+(hi-lo)*i/3,yy=y(v);add('line',{x1:L,x2:W-R,y1:yy,y2:yy,stroke:'#dce6df'});add('text',{x:L-8,y:yy+4,'text-anchor':'end',fill:'#68786e','font-size':11},Intl.NumberFormat('ko-KR',{notation:'compact',maximumFractionDigits:1}).format(v));}
 if(lo<0&&hi>0)add('line',{x1:L,x2:W-R,y1:y(0),y2:y(0),stroke:'#71867a','stroke-dasharray':'4 4'});
 const draw=(list,color,dashed)=>{let d='';list.forEach((p,i)=>{const gap=i>0&&p.segment!=null&&p.segment!==list[i-1].segment;d+=(i===0||gap?'M':'L')+x(p,i).toFixed(2)+' '+y(p.value).toFixed(2)+' ';});add('path',{d,fill:'none',stroke:color,'stroke-width':2.5,...(dashed?{'stroke-dasharray':'6 4'}:{})});};draw(all,'#3e7358',false);if(other.length===all.length)draw(other,'#4284be',true);
 const cursor=add('circle',{cx:x(all.at(-1),all.length-1),cy:y(all.at(-1).value),r:4,fill:'#234b37'}),readout=node('p',null,'readout');const display=i=>{const p=all[i];cursor.setAttribute('cx',x(p,i));cursor.setAttribute('cy',y(p.value));readout.textContent=(time?stamp(p.t):p.label||String(i))+' · '+amount(p.value)+' '+unit+(other[i]?' / 과거 '+amount(other[i].value)+' '+unit:'');};display(all.length-1);
 svg.addEventListener('pointermove',e=>{const r=svg.getBoundingClientRect(),pos=(e.clientX-r.left)/r.width*W;let best=0;for(let i=1;i<all.length;i++)if(Math.abs(x(all[i],i)-pos)<Math.abs(x(all[best],best)-pos))best=i;display(best);});
 const range=node('input');range.type='range';range.min='0';range.max=String(all.length-1);range.value=range.max;range.setAttribute('aria-label','관측 시점 선택');range.addEventListener('input',()=>display(+range.value));const labels=node('div',null,'axis');labels.append(node('span',time?stamp(all[0].t):all[0].label),node('span',time?stamp(all.at(-1).t):all.at(-1).label));wrap.append(readout,svg,labels,range);return wrap;
}
function visual(v){const e=card(v.title,'visual'),p=(v.points||[]).filter(p=>typeof p.value==='number'&&Number.isFinite(p.value));if(v.kind==='bars')e.append(bars(p.map(p=>({...p,text:amount(p.value)+' '+(v.unit||'')}))));else if(v.kind==='range'&&Number.isFinite(v.percentile)){const rank=Math.max(0,Math.min(100,v.percentile));e.append(node('p',`과거 관측의 ${Math.round(rank)}%보다 많은 수준`));const meter=node('meter');meter.min=0;meter.max=100;meter.value=rank;meter.setAttribute('aria-label','과거 관측 대비 위치');e.append(meter);}else if(v.kind==='line'){
  const h=v.history,valid=pts=>Array.isArray(pts)&&pts.length===p.length&&pts.length===(h?.window_hours??-2)+1&&pts.every(x=>Number.isFinite(x.value))&&pts[0]?.value===0;
  const peaks=(h?.price_peaks||[]).filter(q=>valid(q.points)&&Math.abs(q.points.at(-1).value-q.net)<.01);const choices=node('div',null,'choices'),body=node('div');
  const show=peak=>{body.replaceChildren();let compare=[];if(peak){compare=peak.points;prose(body,`현재 ${amount(h.current)} ${v.unit||''}\n${peak.year}년 가격 고점 전 ${amount(peak.net)} ${v.unit||''}`);body.append(node('small',`비교 구간 · ${stamp(peak.from)} → ${stamp(peak.to)}`));}else if(h){if(valid(h.maximum_points)&&Math.abs(h.maximum_points.at(-1).value-h.maximum)<.01)compare=h.maximum_points;prose(body,`현재 누적 ${amount(h.current)} ${v.unit||''}\n최근 1년 같은 시간 최대 ${amount(h.maximum)} ${v.unit||''}`);}
   if(compare.length)body.append(node('small','초록 실선 · 현재 / 파랑 점선 · '+(peak?`${peak.year}년 고점 전`:'과거 최대 구간')));body.append(plot(p,v.unit||'',compare));if(h)body.append(node('small',`같은 ${h.window_hours}시간 비교 · 과거 저점부터의 누적이나 상승 확률이 아니에요. 거래 규모 차이도 있어 금액만으로 고점을 판단할 수 없어요.`));};
  if(peaks.length){const options=[{label:'최근 1년 최대',value:null},...peaks.slice().reverse().map(q=>({label:q.year+' 고점',value:q}))];options.forEach(o=>{const b=node('button',o.label);b.onclick=()=>{choices.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');show(o.value);};b.setAttribute('aria-pressed',String(o.value?.year===2025));choices.append(b);});e.append(choices);}show(peaks.find(p=>p.year===2025)||null);e.append(body);
 }prose(e,v.caption);if(v.observed_at)e.append(node('small','자료 시각 · '+stamp(v.observed_at)));source(e,v.source_url);return e;}
function render(){const r=article.release||{},d=r.detail||{},story=d.story||{};const content=$('content');content.replaceChildren();$('title').textContent=clean(article.article_title||r.heading||article.title);$('time').textContent=stamp(article.at);document.title=$('title').textContent+' · WITH FINDEX';
 const intro=card('결론부터 보면','conclusion');const headline=clean(story.conclusion||d.headline||article.title),summary=clean(story.summary||d.answer||r.summary||article.summary);intro.append(node('h3',headline));if(summary&&summary!==headline)prose(intro,summary);content.append(intro);
 const charts=r.market_charts||[],assets=[...new Set([...charts.map(c=>c.symbol),...(d.visuals||[]).map(v=>v.asset),...(d.sections||[]).map(s=>s.asset)].filter(Boolean))];if(assets.length){if(!assets.includes(selected))selected=assets[0];const tabs=node('nav',null,'asset-tabs');tabs.setAttribute('aria-label','자산 선택');assets.forEach(asset=>{const b=node('button',asset==='BTCUSDT'?'비트코인':asset==='ETHUSDT'?'이더리움':asset);b.setAttribute('aria-pressed',String(asset===selected));b.onclick=()=>{selected=asset;render();};tabs.append(b);});content.append(tabs);}
 const matches=a=>!a||!selected||a===selected;
 for(const c of charts.filter(c=>matches(c.symbol))){const e=card(c.label||c.symbol);e.append(node('p',c.baseline_label),plot(c.points||[],(c.provider||'').includes('USDT')?'USDT':'',[],true),node('small',[c.recent_label,c.provider,stamp(c.observed_at)].filter(Boolean).join(' · ')));source(e,c.source_url);content.append(e);}
 for(const f of r.figures||article.figures||[])content.append(figure(f));
 const sections=d.sections||article.sections||[],visuals=(d.visuals||[]).filter(v=>matches(v.asset)),shown=new Set();
 for(const s of displaySections(sections.filter(s=>matches(s.asset)),[headline,summary])){if(!clean(s.body))continue;const e=card(s.title);prose(e,s.body);content.append(e);for(const v of visuals.filter(v=>(s.evidenceIds||[]).includes(v.id)&&!shown.has(v.id))){content.append(visual(v));shown.add(v.id);}}
 for(const v of visuals.filter(v=>!shown.has(v.id)))content.append(visual(v));
 for(const p of (d.prices||[]).filter(p=>matches(p.coin==='BTC'?'BTCUSDT':p.coin==='ETH'?'ETHUSDT':p.coin))){const e=card(p.coin+' · 발표 후 가격 흐름');const stages=(p.stages||[]).filter(s=>Number.isFinite(s.value)&&Number.isFinite(s.time));if(stages.length===3){e.append(node('small','발표 직전 가격 대비 · %'),plot(stages.map(s=>({t:s.time,value:s.value,label:s.label})), '%',[],true));stages.forEach(s=>{e.append(node('h3',s.label+' · '+amount(s.value)+'%'));prose(e,s.body);});}else e.append(plot((p.bars||[]).map(b=>({t:b.t,value:b.c})), 'USDT',[],true));e.append(node('small',[p.source,p.endpoint,stamp(p.checked_at)].filter(Boolean).join(' · ')));source(e,p.source_url);content.append(e);}
 const caution=clean(story.caution||article.caution);if(caution){const e=card('함께 확인할 점');prose(e,caution);content.append(e);}if(d.gaps?.length){const e=card('아직 확인되지 않은 점');d.gaps.forEach(t=>prose(e,t));content.append(e);}
 const refs=[...(d.evidence||[]),...(story.references||[])],seen=new Set();const sources=card('출처와 확인 시각');for(const ref of refs){const url=safeURL(ref.url||ref.source_url);if(url&&!seen.has(url)){source(sources,url,ref.title||'원문 보기 ↗');seen.add(url);}}if(!seen.has(article.source_url))source(sources,article.source_url);if(d.checked_at)sources.append(node('small','분석 확인 · '+stamp(d.checked_at)));content.append(sources);
 $('notice').textContent=['m','s'].includes(kind)?'이 링크는 최신 분석으로 갱신됩니다. 기준 시각을 확인해 주세요.':'';
}
async function load(){$('retry').hidden=true;$('notice').textContent='';try{if(!['n','c','m','s'].includes(kind)||id.length>80||(['n','c'].includes(kind)&&!(/^[1-9]\d{0,17}$/.test(id))))throw Error('invalid');const response=await fetch(API+'/rest/v1/rpc/read_shared_content',{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json'},body:JSON.stringify({p_kind:kind,p_id:id}),signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('network');article=await response.json();if(!article)throw Error('missing');render();}catch(e){$('content').replaceChildren();$('title').textContent=e.message==='invalid'?'올바르지 않은 공유 주소예요.':e.message==='missing'?'공개된 내용을 찾을 수 없어요.':'내용을 불러오지 못했어요.';$('retry').hidden=['invalid','missing'].includes(e.message);}}
$('retry').onclick=load;$('share').onclick=async()=>{try{if(navigator.share)await navigator.share({title:document.title,url:canonical.href});else{await navigator.clipboard.writeText(canonical.href);$('notice').textContent='공유 링크를 복사했어요.';}}catch(e){if(e.name!=='AbortError')window.prompt('주소를 복사해 주세요.',canonical.href);}};
load();
